name: CI
on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'pnpm'

      # Build frontend
      - run: cd frontend && pnpm install
      - run: cd frontend && pnpm build

      # Run tests
      - run: pnpm install
      - run: pnpm format
      - run: pnpm lint
      - run: pnpm test
